function calcular_volumen_gui()
% CALCULADORA_VOLUMENES_GUI Interfaz gráfica mejorada con modo oscuro
% Esta función crea una GUI moderna y redimensionable para calcular volúmenes

    % Variables globales para los controles y tema
    global edit_inputs text_resultado text_formula text_info current_figure;
    global uipanel_seleccion uipanel_formula uipanel_datos uipanel_resultados uipanel_controles;
    global dark_mode theme_colors;
    
    current_figure = 'cubo';
    dark_mode = true; % Empezar en modo oscuro
    
    % Definir colores para ambos temas
    setup_theme_colors();
    
    % Crear la figura principal con redimensionamiento
    fig = figure('Name', 'Calculadora de Volúmenes - Modo Oscuro', ...
                 'Position', [100, 100, 900, 750], ...
                 'Resize', 'on', ...
                 'Color', theme_colors.bg_main, ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none', ...
                 'SizeChangedFcn', @resize_callback, ...
                 'CloseRequestFcn', @close_callback);
    
    % Título principal
    title_text = uicontrol('Style', 'text', ...
        'String', '🔮 CALCULADORA DE VOLÚMENES', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.92, 0.7, 0.06], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', theme_colors.bg_main, ...
        'ForegroundColor', theme_colors.text_title, ...
        'HorizontalAlignment', 'left');
    
    % Switch para cambiar tema
    theme_switch = uicontrol('Style', 'togglebutton', ...
        'String', '🌙 Modo Claro', ...
        'Units', 'normalized', ...
        'Position', [0.8, 0.92, 0.15, 0.06], ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', theme_colors.button_bg, ...
        'ForegroundColor', theme_colors.text_primary, ...
        'Value', dark_mode, ...
        'Callback', @toggle_theme);
    
    % Panel de selección de figura con mejor diseño
    uipanel_seleccion = uipanel('Title', '📐 Seleccionar Figura 3D', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.75, 0.96, 0.15], ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_primary, ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BorderType', 'line', ...
        'HighlightColor', theme_colors.border);
    
    create_figure_buttons();
    
    % Panel de fórmula mejorado
    uipanel_formula = uipanel('Title', '📊 Fórmula Matemática', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.62, 0.96, 0.11], ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_primary, ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BorderType', 'line', ...
        'HighlightColor', theme_colors.border);
    
    text_formula = uicontrol('Parent', uipanel_formula, ...
        'Style', 'text', ...
        'String', 'V = lado³', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.1, 0.96, 0.7], ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_formula, ...
        'HorizontalAlignment', 'center');
    
    % Panel de entrada de datos mejorado
    uipanel_datos = uipanel('Title', '⚙️ Datos de Entrada', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.35, 0.96, 0.25], ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_primary, ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BorderType', 'line', ...
        'HighlightColor', theme_colors.border);
    
    edit_inputs = {};
    
    % Botón calcular mejorado
    calc_button = uicontrol('Parent', uipanel_datos, ...
        'Style', 'pushbutton', ...
        'String', '🧮 CALCULAR VOLUMEN', ...
        'Units', 'normalized', ...
        'Position', [0.35, 0.1, 0.3, 0.25], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', theme_colors.button_calc, ...
        'ForegroundColor', theme_colors.text_button, ...
        'Callback', @calcular_volumen_callback);
    
    % Panel de resultados mejorado
    uipanel_resultados = uipanel('Title', '📈 Resultados del Cálculo', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.18, 0.96, 0.15], ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_primary, ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BorderType', 'line', ...
        'HighlightColor', theme_colors.border);
    
    text_resultado = uicontrol('Parent', uipanel_resultados, ...
        'Style', 'text', ...
        'String', '✨ Seleccione una figura e ingrese los datos...', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.55, 0.96, 0.35], ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', theme_colors.result_bg, ...
        'ForegroundColor', theme_colors.text_result, ...
        'HorizontalAlignment', 'center');
    
    text_info = uicontrol('Parent', uipanel_resultados, ...
        'Style', 'text', ...
        'String', '', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.1, 0.96, 0.35], ...
        'FontSize', 10, ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_secondary, ...
        'HorizontalAlignment', 'center');
    
    % Panel de controles mejorado
    uipanel_controles = uipanel('Title', '🛠️ Herramientas', ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.02, 0.96, 0.14], ...
        'BackgroundColor', theme_colors.panel_bg, ...
        'ForegroundColor', theme_colors.text_primary, ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BorderType', 'line', ...
        'HighlightColor', theme_colors.border);
    
    create_control_buttons();
    
    % Inicializar con cubo
    cambiar_figura('cubo');
    
    % --- FUNCIONES DE CONFIGURACIÓN ---
    function setup_theme_colors()
        if dark_mode
            % Tema oscuro moderno
            theme_colors.bg_main = [0.12, 0.12, 0.15];
            theme_colors.panel_bg = [0.18, 0.18, 0.22];
            theme_colors.button_bg = [0.25, 0.25, 0.3];
            theme_colors.button_calc = [0.2, 0.6, 0.3];
            theme_colors.result_bg = [0.15, 0.2, 0.15];
            theme_colors.text_primary = [0.9, 0.9, 0.95];
            theme_colors.text_secondary = [0.7, 0.7, 0.8];
            theme_colors.text_title = [0.4, 0.8, 1.0];
            theme_colors.text_formula = [1.0, 0.8, 0.4];
            theme_colors.text_result = [0.4, 1.0, 0.6];
            theme_colors.text_button = [1, 1, 1];
            theme_colors.border = [0.4, 0.4, 0.5];
            theme_colors.edit_bg = [0.25, 0.25, 0.3];
        else
            % Tema claro moderno
            theme_colors.bg_main = [0.96, 0.96, 0.98];
            theme_colors.panel_bg = [1.0, 1.0, 1.0];
            theme_colors.button_bg = [0.9, 0.9, 0.95];
            theme_colors.button_calc = [0.2, 0.7, 0.4];
            theme_colors.result_bg = [0.9, 1.0, 0.9];
            theme_colors.text_primary = [0.1, 0.1, 0.2];
            theme_colors.text_secondary = [0.4, 0.4, 0.5];
            theme_colors.text_title = [0.1, 0.3, 0.8];
            theme_colors.text_formula = [0.6, 0.3, 0.1];
            theme_colors.text_result = [0.1, 0.6, 0.2];
            theme_colors.text_button = [1, 1, 1];
            theme_colors.border = [0.7, 0.7, 0.8];
            theme_colors.edit_bg = [1, 1, 1];
        end
    end
    
    function create_figure_buttons()
        figuras = {'cubo', 'prisma_rectangular', 'cilindro', 'cono', ...
                   'esfera', 'piramide', 'tronco_cono', 'prisma_triangular'};
        nombres = {'🎲 Cubo', '📦 Prisma Rect.', '🥫 Cilindro', '🍦 Cono', ...
                   '⚽ Esfera', '🔺 Pirámide', '🪣 Tronco Cono', '🔻 Prisma Triang.'};
        colores = {[1.0, 0.7, 0.5], [0.7, 1.0, 0.5], [0.5, 0.7, 1.0], [1.0, 0.5, 0.7], ...
                   [0.7, 0.5, 1.0], [1.0, 1.0, 0.5], [0.5, 1.0, 1.0], [1.0, 0.7, 0.7]};
        
        for i = 1:8
            row = floor((i-1)/4);
            col = mod(i-1, 4);
            x = 0.02 + col * 0.24;
            y = 0.6 - row * 0.45;
            
            color = colores{i};
            if dark_mode
                color = color * 0.7; % Oscurecer colores en modo oscuro
            end
            
            uicontrol('Parent', uipanel_seleccion, ...
                'Style', 'pushbutton', ...
                'String', nombres{i}, ...
                'Units', 'normalized', ...
                'Position', [x, y, 0.22, 0.35], ...
                'FontSize', 9, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', color, ...
                'ForegroundColor', theme_colors.text_primary, ...
                'Callback', @(src,evt) cambiar_figura(figuras{i}));
        end
    end
    
    function create_control_buttons()
        botones = {{'📋 Mostrar Fórmulas', @mostrar_todas_formulas, [0.7, 0.7, 1.0]}, ...
                   {'🧹 Limpiar', @limpiar_campos, [1.0, 0.8, 0.6]}, ...
                   {'❌ Salir', @(~,~) close(fig), [1.0, 0.6, 0.6]}};
        
        for i = 1:3
            x = 0.1 + (i-1) * 0.25;
            color = botones{i}{3};
            if dark_mode
                color = color * 0.8;
            end
            
            uicontrol('Parent', uipanel_controles, ...
                'Style', 'pushbutton', ...
                'String', botones{i}{1}, ...
                'Units', 'normalized', ...
                'Position', [x, 0.3, 0.2, 0.4], ...
                'FontSize', 10, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', color, ...
                'ForegroundColor', theme_colors.text_primary, ...
                'Callback', botones{i}{2});
        end
    end
    
    % --- FUNCIONES PRINCIPALES ---
    function toggle_theme(src, ~)
        dark_mode = get(src, 'Value');
        setup_theme_colors();
        update_all_colors();
        
        if dark_mode
            set(src, 'String', '☀️ Modo Claro');
            set(fig, 'Name', 'Calculadora de Volúmenes - Modo Oscuro');
        else
            set(src, 'String', '🌙 Modo Oscuro');
            set(fig, 'Name', 'Calculadora de Volúmenes - Modo Claro');
        end
    end
    
    function update_all_colors()
        % Actualizar figura principal
        set(fig, 'Color', theme_colors.bg_main);
        
        % Actualizar todos los elementos
        all_children = findall(fig);
        for i = 1:length(all_children)
            obj = all_children(i);
            if isprop(obj, 'BackgroundColor') && isprop(obj, 'Type')
                switch get(obj, 'Type')
                    case 'uipanel'
                        set(obj, 'BackgroundColor', theme_colors.panel_bg);
                        set(obj, 'ForegroundColor', theme_colors.text_primary);
                    case 'uicontrol'
                        style = get(obj, 'Style');
                        if strcmp(style, 'text')
                            parent = get(obj, 'Parent');
                            if obj == text_resultado
                                set(obj, 'BackgroundColor', theme_colors.result_bg);
                                set(obj, 'ForegroundColor', theme_colors.text_result);
                            elseif obj == text_formula
                                set(obj, 'BackgroundColor', theme_colors.panel_bg);
                                set(obj, 'ForegroundColor', theme_colors.text_formula);
                            else
                                set(obj, 'BackgroundColor', theme_colors.panel_bg);
                                set(obj, 'ForegroundColor', theme_colors.text_primary);
                            end
                        elseif strcmp(style, 'edit')
                            set(obj, 'BackgroundColor', theme_colors.edit_bg);
                            set(obj, 'ForegroundColor', theme_colors.text_primary);
                        end
                end
            end
        end
        
        % Recrear botones con nuevos colores
        delete(get(uipanel_seleccion, 'Children'));
        delete(get(uipanel_controles, 'Children'));
        create_figure_buttons();
        create_control_buttons();
        
        % Recrear botón calcular
        calc_button = uicontrol('Parent', uipanel_datos, ...
            'Style', 'pushbutton', ...
            'String', '🧮 CALCULAR VOLUMEN', ...
            'Units', 'normalized', ...
            'Position', [0.35, 0.1, 0.3, 0.25], ...
            'FontSize', 11, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', theme_colors.button_calc, ...
            'ForegroundColor', theme_colors.text_button, ...
            'Callback', @calcular_volumen_callback);
    end
    
    function cambiar_figura(tipo)
        current_figure = tipo;
        
        % Limpiar campos anteriores
        for i = 1:length(edit_inputs)
            if ishandle(edit_inputs{i}.label)
                delete(edit_inputs{i}.label);
            end
            if ishandle(edit_inputs{i}.edit)
                delete(edit_inputs{i}.edit);
            end
        end
        edit_inputs = {};
        
        % Configurar fórmula y campos según el tipo
        switch tipo
            case 'cubo'
                set(text_formula, 'String', 'V = lado³');
                crear_campo('📏 Lado:', 0.1, 0.7);
                
            case 'prisma_rectangular'
                set(text_formula, 'String', 'V = largo × ancho × altura');
                crear_campo('📐 Largo:', 0.05, 0.7);
                crear_campo('📐 Ancho:', 0.35, 0.7);
                crear_campo('📐 Altura:', 0.65, 0.7);
                
            case 'cilindro'
                set(text_formula, 'String', 'V = π × radio² × altura');
                crear_campo('⭕ Radio:', 0.15, 0.7);
                crear_campo('📐 Altura:', 0.55, 0.7);
                
            case 'cono'
                set(text_formula, 'String', 'V = (1/3) × π × radio² × altura');
                crear_campo('⭕ Radio:', 0.15, 0.7);
                crear_campo('📐 Altura:', 0.55, 0.7);
                
            case 'esfera'
                set(text_formula, 'String', 'V = (4/3) × π × radio³');
                crear_campo('⭕ Radio:', 0.35, 0.7);
                
            case 'piramide'
                set(text_formula, 'String', 'V = (1/3) × área_base × altura');
                crear_campo('📊 Área base:', 0.15, 0.7);
                crear_campo('📐 Altura:', 0.55, 0.7);
                
            case 'tronco_cono'
                set(text_formula, 'String', 'V = (1/3) × π × h × (r₁² + r₁×r₂ + r₂²)');
                crear_campo('⭕ Radio mayor:', 0.05, 0.7);
                crear_campo('⭕ Radio menor:', 0.35, 0.7);
                crear_campo('📐 Altura:', 0.65, 0.7);
                
            case 'prisma_triangular'
                set(text_formula, 'String', 'V = (1/2) × base × altura_base × longitud');
                crear_campo('📐 Base △:', 0.05, 0.7);
                crear_campo('📐 Altura △:', 0.35, 0.7);
                crear_campo('📐 Longitud:', 0.65, 0.7);
        end
        
        % Limpiar resultados
        set(text_resultado, 'String', '✨ Ingrese los datos y presione calcular...');
        set(text_info, 'String', '');
    end
    
    function crear_campo(etiqueta, x, y)
        n = length(edit_inputs) + 1;
        
        edit_inputs{n}.label = uicontrol('Parent', uipanel_datos, ...
            'Style', 'text', ...
            'String', etiqueta, ...
            'Units', 'normalized', ...
            'Position', [x, y, 0.25, 0.15], ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', theme_colors.panel_bg, ...
            'ForegroundColor', theme_colors.text_primary, ...
            'HorizontalAlignment', 'left');
        
        edit_inputs{n}.edit = uicontrol('Parent', uipanel_datos, ...
            'Style', 'edit', ...
            'Units', 'normalized', ...
            'Position', [x, y-0.2, 0.25, 0.15], ...
            'FontSize', 10, ...
            'BackgroundColor', theme_colors.edit_bg, ...
            'ForegroundColor', theme_colors.text_primary);
    end
    
    function calcular_volumen_callback(~, ~)
        try
            % Obtener valores de los campos
            valores = [];
            for i = 1:length(edit_inputs)
                valor = str2double(get(edit_inputs{i}.edit, 'String'));
                if isnan(valor)
                    set(text_resultado, 'String', '⚠️ Error: Todos los campos deben contener números válidos');
                    set(text_info, 'String', '');
                    return;
                end
                if valor <= 0
                    set(text_resultado, 'String', '⚠️ Error: Todas las dimensiones deben ser positivas');
                    set(text_info, 'String', '');
                    return;
                end
                valores(end+1) = valor;
            end
            
            % Calcular según el tipo seleccionado
            [volumen, info_adicional] = calcular_segun_tipo(current_figure, valores);
            
            % Mostrar resultado con formato mejorado
            if volumen < 1
                vol_str = sprintf('%.6f', volumen);
            elseif volumen < 1000
                vol_str = sprintf('%.4f', volumen);
            else
                vol_str = sprintf('%.2f', volumen);
            end
            
            set(text_resultado, 'String', sprintf('📊 Volumen: %s unidades³', vol_str));
            set(text_info, 'String', info_adicional);
            
        catch ME
            set(text_resultado, 'String', '❌ Error en el cálculo');
            set(text_info, 'String', ME.message);
        end
    end
    
    function [volumen, info] = calcular_segun_tipo(figura, valores)
        info = '';
        
        switch figura
            case 'cubo'
                volumen = valores(1)^3;
                area_superficie = 6 * valores(1)^2;
                diagonal = valores(1) * sqrt(3);
                info = sprintf('📐 Área superficie: %.4f | 🔷 Diagonal: %.4f', area_superficie, diagonal);
                
            case 'prisma_rectangular'
                volumen = valores(1) * valores(2) * valores(3);
                area_superficie = 2 * (valores(1)*valores(2) + valores(1)*valores(3) + valores(2)*valores(3));
                info = sprintf('📏 Dimensiones: %.2f × %.2f × %.2f | 📐 Área superficie: %.4f', ...
                              valores(1), valores(2), valores(3), area_superficie);
                
            case 'cilindro'
                volumen = pi * valores(1)^2 * valores(2);
                area_superficie = 2 * pi * valores(1) * (valores(1) + valores(2));
                info = sprintf('⭕ Radio: %.2f | 📐 Altura: %.2f | 📐 Área superficie: %.4f', ...
                              valores(1), valores(2), area_superficie);
                
            case 'cono'
                volumen = (1/3) * pi * valores(1)^2 * valores(2);
                generatriz = sqrt(valores(1)^2 + valores(2)^2);
                area_superficie = pi * valores(1) * (valores(1) + generatriz);
                info = sprintf('⭕ Radio: %.2f | 📐 Altura: %.2f | 📏 Generatriz: %.4f | 📐 Área: %.4f', ...
                              valores(1), valores(2), generatriz, area_superficie);
                
            case 'esfera'
                volumen = (4/3) * pi * valores(1)^3;
                area_superficie = 4 * pi * valores(1)^2;
                diametro = 2 * valores(1);
                info = sprintf('⭕ Radio: %.2f | 🔷 Diámetro: %.2f | 📐 Área superficie: %.4f', ...
                              valores(1), diametro, area_superficie);
                
            case 'piramide'
                volumen = (1/3) * valores(1) * valores(2);
                info = sprintf('📊 Área base: %.2f | 📐 Altura: %.2f', valores(1), valores(2));
                
            case 'tronco_cono'
                volumen = (1/3) * pi * valores(3) * (valores(1)^2 + valores(1)*valores(2) + valores(2)^2);
                info = sprintf('⭕ Radio mayor: %.2f | ⭕ Radio menor: %.2f | 📐 Altura: %.2f', ...
                              valores(1), valores(2), valores(3));
                
            case 'prisma_triangular'
                area_base = 0.5 * valores(1) * valores(2);
                volumen = area_base * valores(3);
                info = sprintf('📐 Base: %.2f | 📐 Altura △: %.2f | 📐 Longitud: %.2f | 📊 Área base: %.4f', ...
                              valores(1), valores(2), valores(3), area_base);
        end
    end
    
    function mostrar_todas_formulas(~, ~)
        formulas_msg = sprintf(['📐 FÓRMULAS DE VOLUMEN 📐\n\n' ...
            '🎲 Cubo: V = lado³\n' ...
            '📦 Prisma rectangular: V = largo × ancho × altura\n' ...
            '🥫 Cilindro: V = π × radio² × altura\n' ...
            '🍦 Cono: V = (1/3) × π × radio² × altura\n' ...
            '⚽ Esfera: V = (4/3) × π × radio³\n' ...
            '🔺 Pirámide: V = (1/3) × área_base × altura\n' ...
            '🪣 Tronco de cono: V = (1/3) × π × h × (r₁² + r₁×r₂ + r₂²)\n' ...
            '🔻 Prisma triangular: V = (1/2) × base × altura_base × longitud\n\n' ...
            '💡 Todas las dimensiones deben ser positivas\n' ...
            '📊 Los resultados incluyen información adicional']);
        
        msgbox(formulas_msg, '📐 Fórmulas de Volumen', 'help');
    end
    
    function limpiar_campos(~, ~)
        for i = 1:length(edit_inputs)
            set(edit_inputs{i}.edit, 'String', '');
        end
        set(text_resultado, 'String', '🧹 Campos limpiados. Ingrese nuevos datos...');
        set(text_info, 'String', '');
    end
    
    function resize_callback(~, ~)
        % La función se ejecuta automáticamente al redimensionar
        % Los elementos con 'Units' = 'normalized' se ajustan automáticamente
    end
    
    function close_callback(~, ~)
        selection = questdlg('¿Está seguro que desea cerrar la calculadora?', ...
                           'Confirmar Cierre', ...
                           'Sí', 'No', 'No');
        if strcmp(selection, 'Sí')
            delete(fig);
        end
    end
end