function SegundaLeyNewtonGui()
    % Interfaz gráfica para la Segunda Ley de Newton: F = m * a

    % Crear la figura principal con tamaño estándar
    fig = uifigure('Name', 'Segunda Ley de Newton', ...
                   'Position', [100, 100, 1280, 720], ...
                   'Color', [0.1, 0.1, 0.1]);

    % Barra superior azul y título
    uipanel(fig, 'Position', [0, 670, 1280, 50], ...
            'BackgroundColor', [0.22, 0.51, 0.78], 'BorderType', 'none');
    uilabel(fig, 'Text', 'SEGUNDA LEY DE NEWTON: F = m * a', ...
        'Position', [0, 670, 1280, 50], ...
        'FontSize', 26, 'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', 'none', ...
        'FontColor', 'white');

    % Panel EXPLICACION
    panel_explicacion = uipanel(fig, 'Title', 'EXPLICACION DE LA FUNCION O METODO', ...
        'Position', [30, 600, 1220, 60], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);
    texto_explicacion = uitextarea(panel_explicacion, ...
        'Position', [10, 10, 1200, 30], ...
        'Editable', 'off', ...
        'FontSize', 12, ...
        'FontColor', 'white', ...
        'BackgroundColor', [0.18, 0.18, 0.18], ...
        'Value', {'Calcula la fuerza resultante aplicando F = m * a. Ingrese los valores y presione CALCULAR.'});

    % Panel INICIO DE DATOS
    panel_datos = uipanel(fig, 'Title', 'INGRESO DE DATOS', ...
        'Position', [30, 430, 400, 150], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);

    uilabel(panel_datos, 'Text', 'Masa (kg):', ...
        'Position', [20, 80, 100, 30], ...
        'FontSize', 13, 'FontColor', 'white', 'FontWeight', 'bold');
    campo_masa = uieditfield(panel_datos, 'numeric', ...
        'Position', [130, 85, 220, 25], ...
        'Value', 1, 'FontColor', 'white', ...
        'BackgroundColor', [0.2, 0.2, 0.2]);

    uilabel(panel_datos, 'Text', 'Aceleración (m/s²):', ...
        'Position', [20, 45, 120, 30], ...
        'FontSize', 13, 'FontColor', 'white', 'FontWeight', 'bold');
    campo_aceleracion = uieditfield(panel_datos, 'numeric', ...
        'Position', [150, 50, 200, 25], ...
        'Value', 0, 'FontColor', 'white', ...
        'BackgroundColor', [0.2, 0.2, 0.2]);

    btn_calcular = uibutton(panel_datos, 'Text', 'CALCULAR', ...
        'Position', [20, 10, 120, 30], ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.3, 0.7, 0.3], ...
        'FontColor', 'white', ...
        'ButtonPushedFcn', @(btn,event) calcular_fuerza());

    % Panel RESULTADOS
    panel_resultados = uipanel(fig, 'Title', 'RESULTADOS', ...
        'Position', [450, 430, 400, 150], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);
    texto_resultados = uitextarea(panel_resultados, ...
        'Position', [10, 10, 380, 110], ...
        'Editable', 'off', ...
        'FontSize', 13, ...
        'FontColor', 'white', ...
        'BackgroundColor', [0.18, 0.18, 0.18]);

    % Panel GRAFICA
    panel_grafica = uipanel(fig, 'Title', '', ...
        'Position', [30, 30, 1220, 380], ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);
    axes_grafica = uiaxes(panel_grafica, ...
        'Position', [40, 40, 1140, 320], ...
        'BackgroundColor', [0.18, 0.18, 0.18], ...
        'XColor', 'white', 'YColor', 'white', ...
        'FontSize', 13);
    % Etiqueta central
    text(axes_grafica, 0.5, 0.5, 'GRAFICA', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 20, 'Color', [1 1 1 0.2]);

    % --- Función para calcular la fuerza y graficar ---
    function calcular_fuerza()
        m = campo_masa.Value;
        a = campo_aceleracion.Value;
        F = m * a;
        texto_resultados.Value = {sprintf('Masa: %.2f kg', m), ...
                                  sprintf('Aceleración: %.2f m/s²', a), ...
                                  sprintf('Fuerza: %.2f N', F)};
        % Graficar F vs a
        a_vals = linspace(-10, 10, 100);
        F_vals = m * a_vals;
        plot(axes_grafica, a_vals, F_vals, 'b-', 'LineWidth', 2);
        hold(axes_grafica, 'on');
        plot(axes_grafica, a, F, 'ro', 'MarkerSize', 10, 'LineWidth', 2);
        hold(axes_grafica, 'off');
        xlabel(axes_grafica, 'Aceleración (m/s²)');
        ylabel(axes_grafica, 'Fuerza (N)');
        title(axes_grafica, sprintf('Fuerza vs Aceleración (Masa = %.2f kg)', m), 'Color', 'white');
        grid(axes_grafica, 'on');
    end
end