function TerceraLeyNewtonGui()
    % Interfaz gráfica para la Tercera Ley de Newton: Acción y Reacción

    fig = uifigure('Name', 'Tercera Ley de Newton', ...
                   'Position', [100, 100, 1280, 720], ...
                   'Color', [0.1, 0.1, 0.1]);

    % Barra superior azul y título
    uipanel(fig, 'Position', [0, 670, 1280, 50], ...
            'BackgroundColor', [0.22, 0.51, 0.78], 'BorderType', 'none');
    uilabel(fig, 'Text', 'TERCERA LEY DE NEWTON: ACCIÓN Y REACCIÓN', ...
        'Position', [0, 670, 1280, 50], ...
        'FontSize', 26, 'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', 'none', ...
        'FontColor', 'white');

    % Panel EXPLICACION
    panel_explicacion = uipanel(fig, 'Title', 'EXPLICACION DE LA FUNCION O METODO', ...
        'Position', [30, 600, 1220, 60], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);
    texto_explicacion = uitextarea(panel_explicacion, ...
        'Position', [10, 10, 1200, 30], ...
        'Editable', 'off', ...
        'FontSize', 12, ...
        'FontColor', 'white', ...
        'BackgroundColor', [0.18, 0.18, 0.18], ...
        'Value', {'Simula la Tercera Ley de Newton: toda acción tiene una reacción igual y opuesta.'; ...
                  'Ingrese los valores y presione CALCULAR.'});

    % Panel INGRESO DE DATOS
    panel_datos = uipanel(fig, 'Title', 'INGRESO DE DATOS', ...
        'Position', [30, 430, 400, 150], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);

    uilabel(panel_datos, 'Text', 'Masa cuerpo A (kg):', ...
        'Position', [20, 100, 140, 25], ...
        'FontSize', 13, 'FontColor', 'white', 'FontWeight', 'bold');
    campo_mA = uieditfield(panel_datos, 'numeric', ...
        'Position', [170, 100, 180, 25], ...
        'Value', 1, 'FontColor', 'white', ...
        'BackgroundColor', [0.2, 0.2, 0.2]);

    uilabel(panel_datos, 'Text', 'Masa cuerpo B (kg):', ...
        'Position', [20, 65, 140, 25], ...
        'FontSize', 13, 'FontColor', 'white', 'FontWeight', 'bold');
    campo_mB = uieditfield(panel_datos, 'numeric', ...
        'Position', [170, 65, 180, 25], ...
        'Value', 1, 'FontColor', 'white', ...
        'BackgroundColor', [0.2, 0.2, 0.2]);

    uilabel(panel_datos, 'Text', 'Fuerza de acción (N):', ...
        'Position', [20, 30, 140, 25], ...
        'FontSize', 13, 'FontColor', 'white', 'FontWeight', 'bold');
    campo_Faccion = uieditfield(panel_datos, 'numeric', ...
        'Position', [170, 30, 180, 25], ...
        'Value', 10, 'FontColor', 'white', ...
        'BackgroundColor', [0.2, 0.2, 0.2]);

    btn_calcular = uibutton(panel_datos, 'Text', 'CALCULAR', ...
        'Position', [20, -10, 120, 30], ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.3, 0.7, 0.3], ...
        'FontColor', 'white', ...
        'ButtonPushedFcn', @(btn,event) calcular_tercera_ley());

    % Panel RESULTADOS
    panel_resultados = uipanel(fig, 'Title', 'RESULTADOS', ...
        'Position', [450, 430, 400, 150], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);
    texto_resultados = uitextarea(panel_resultados, ...
        'Position', [10, 10, 380, 110], ...
        'Editable', 'off', ...
        'FontSize', 13, ...
        'FontColor', 'white', ...
        'BackgroundColor', [0.18, 0.18, 0.18]);

    % Panel GRAFICA
    panel_grafica = uipanel(fig, 'Title', '', ...
        'Position', [30, 30, 1220, 380], ...
        'BackgroundColor', [0.13, 0.13, 0.13], ...
        'ForegroundColor', [0.3, 0.6, 1]);
    % Dos gráficas del mismo tamaño, alineadas horizontalmente
    axes_grafica1 = uiaxes(panel_grafica, ...
        'Position', [40, 40, 560, 320], ...
        'BackgroundColor', [0.18, 0.18, 0.18], ...
        'XColor', 'white', 'YColor', 'white', ...
        'FontSize', 13);
    axes_grafica2 = uiaxes(panel_grafica, ...
        'Position', [620, 40, 560, 320], ...
        'BackgroundColor', [0.18, 0.18, 0.18], ...
        'XColor', 'white', 'YColor', 'white', ...
        'FontSize', 13);

    % Etiqueta central
    text(axes_grafica1, 0.5, 0.5, 'GRAFICA', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 20, 'Color', [1 1 1 0.2]);
    text(axes_grafica2, 0.5, 0.5, 'GRAFICA', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 20, 'Color', [1 1 1 0.2]);

    % --- Función para calcular y graficar ---
    function calcular_tercera_ley()
        mA = campo_mA.Value;
        mB = campo_mB.Value;
        F_accion = campo_Faccion.Value;

        if mA <= 0 || mB <= 0 || F_accion <= 0
            texto_resultados.Value = {'Error: Todos los valores deben ser mayores que cero.'};
            cla(axes_grafica1); cla(axes_grafica2);
            return;
        end

        F_reaccion = -F_accion;
        aB = F_accion / mB;
        aA = F_reaccion / mA;

        texto_resultados.Value = {sprintf('Fuerza de acción: %.2f N (A sobre B)', F_accion), ...
                                  sprintf('Fuerza de reacción: %.2f N (B sobre A)', F_reaccion), ...
                                  sprintf('Aceleración de B: %.2f m/s²', aB), ...
                                  sprintf('Aceleración de A: %.2f m/s² (opuesta)', aA)};

        % Gráfica de fuerzas (quiver)
        cla(axes_grafica1);
        quiver(axes_grafica1, 0, 0, F_accion, 0, 0, 'r', 'LineWidth', 2, 'MaxHeadSize', 1.5); hold(axes_grafica1, 'on');
        quiver(axes_grafica1, 0, 0, F_reaccion, 0, 0, 'b', 'LineWidth', 2, 'MaxHeadSize', 1.5);
        xlim(axes_grafica1, [-1.2*abs(F_accion), 1.2*abs(F_accion)]);
        ylim(axes_grafica1, [-1, 1]);
        axis(axes_grafica1, 'equal');
        grid(axes_grafica1, 'on');
        title(axes_grafica1, 'Fuerzas: Acción y Reacción', 'Color', 'white');
        legend(axes_grafica1, {'Acción (A sobre B)', 'Reacción (B sobre A)'}, 'TextColor', 'white', 'Location', 'northoutside');
        hold(axes_grafica1, 'off');

        % Gráfica de aceleraciones (barras)
        cla(axes_grafica2);
        bar(axes_grafica2, [aA, aB]);
        set(axes_grafica2, 'XTickLabel', {'aA (cuerpo A)', 'aB (cuerpo B)'});
        ylabel(axes_grafica2, 'Aceleración (m/s²)');
        title(axes_grafica2, 'Aceleraciones resultantes', 'Color', 'white');
        grid(axes_grafica2, 'on');
    end
end