function main_calculadora_gui()
    % Crear ventana principal
    fig = uifigure('Name', 'CALCULADORA', 'Position', [500 300 400 450]);

    % Título
    uilabel(fig, ...
        'Text', '=== CALCULADORA ===', ...
        'FontSize', 20, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'Position', [50 400 300 30]);

    % Subtítulo
    uilabel(fig, ...
        'Text', '=== ELIJA UNA OPCIÓN ===', ...
        'FontSize', 14, ...
        'HorizontalAlignment', 'center', ...
        'Position', [50 370 300 25]);

    % Opciones de botones
    opciones = { ...
        '24. CÁLCULO DE ÁREAS', ...
        '25. FUNCIONES DE POTENCIA', ...
        '26. MRUA', ...
        '27. CÁLCULO DE LÍMITES', ...
        '28. RAÍCES MÚLTIPLES', ...
        '29. PUNTO FIJO'};

    callbacks = { ...
        @() calculo_areas_gui() ...
        @() funcion_potencia_gui() ...
        @() mrua_gui() ...
        @() calculo_limites_gui() ...
        @() raices_multiples_gui() ...
        @() punto_fijo_gui()};

    y = 320;
    for i = 1:length(opciones)
        uibutton(fig, ...
            'Text', opciones{i}, ...
            'Position', [80 y 240 30], ...
            'ButtonPushedFcn', @(btn,event) callbacks{i}());
        y = y - 45;
    end

    % Botón salir
    uibutton(fig, ...
        'Text', '0. SALIR', ...
        'Position', [80 60 240 30], ...
        'ButtonPushedFcn', @(btn,event) close(fig));
end
